set nu
set ai
set ts=8
set bg=dark
"코드보는 눈이 좀더 편해짐.
:set t_Co=256

"들여쓰기 설정
set smartindent
"줄번호 설정
set number
"언어별 키워드 하이라이팅 기능
syntax on
"편집창의 배경을 어둡게 설정한다 이에 맞게 텍스트들의 색도 바뀌 것이다
set background=dark
set csprg=/usr/bin/cscope
set csto=0
set cst
set nocsverb
if filereadable("./cscope.out")
        cs add cscope.out
endif
set csverb

filetype on
nmap <F7> :TlistToggle<CR>
let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_Inc_Winwidth = 0
let Tlist_Exit_OnlyWindow = 0
let Tlist_Auto_Open = 0
let Tlist_Use_Right_Window = 1


"=============== NERDTree =============="
let NERDTreeWinPos = "left"
nmap <F9> :NERDTreeToggle<CR>

"=============== source explorer =============="
nmap <F8> :SrcExplToggle<CR>
nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-L> <C-W>l

let g:SrcExpl_winHeight = 8
let g:SrcExpl_refreshTime = 100
let g:SrcExpl_jumpKey = "<ENTER>"
let g:SrcExpl_gobackKey = "<SPACE>"

"일치하는 태그가 존재하는 다음 파일로 이동하기
map <F3> :tnext

"이전 파일로 이동하기
map <F2> :tprevious

"변경사항 저장하기
map <F4> :w

"붙여넣기모드 활성화
map <C-P>y :set paste
map <C-P>n :set nopaste

"라인번호 활성화
map <C-N>y :set nu
map <C-N>n :set nonu

"라인 첫글자 +,- 지우기
map <C-D>+ :%s/^+//g
map <C-D>- :%s/^-//g
map <C-I>i :r! echo "Commented by SeokHoon.Yoon(sh.yoon@lge.com)"



set csprg=/usr/bin/cscope
set csto=0
set cst
set nocsverb
set bg=dark
set autoindent
set smartindent
set hlsearch

if filereadable("./cscope.out")
	cs add cscope.out
else 
	cs add /home/iamyooon/work/000-kernel/mainline_k/cscope.out
"	cs add /home/iamyooon/work/100.android/platform/TCC8930/01.SourceCode/kernel/cscope.out
endif
set csverb


if filereadable("./tags")
	set tag=./tags
else 
	set tag=/home/iamyooon/work/000-kernel/mainline_k/tags
"	set tag=/home/iamyooon/work/100.android/platform/TCC8930/01.SourceCode/kernel/tags
endif

 "find this C symbol
func! Css()
 let css = expand("<cword>")
 new
 exe "cs find s ".css
 if getline(1) == " "
 exe "q!"
 endif
endfunc
nmap ,css :call Css()<cr>


 "find finctions calling this function
func! Csc()
 let csc = expand("<cword>")
 new
 exe "cs find c ".csc
 if getline(1) == " "
  exe "q!"
 endif
endfunc
nmap ,csc :call Csc()<cr>


 "find functions called by this function
func! Csd()
 let csd = expand("<cword>")
 new
 exe "cs find d ".csd
 if getline(1) == " "
  exe "q!"
 endif
endfunc
nmap ,csd :call Csd()<cr>


 "find this definition
func! Csg()
 let csg = expand("<cword>")
 new
 exe "cs find g ".csg
 if getline(1) == " "
  exe "q!"
 endif
endfunc
nmap ,csg :call Csg()<cr>

hi ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$\| \+\ze\t/

" 검색한 문자 하이라이팅
set hlsearch
"=============== key mapping ======================
map <F2> v]}zf
map <F3> zo
map <F4> :Tlist<cr><C-W><C-W>
map <F5> :buffers<cr>

map <PageUp> <C-U><C-U>
map <PageDown> <C-D><C-D>

map <c-h> <c-w>h
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
