CC ?= gcc
all:
	$(CC) print_addr_or_value.c -o print_addr_or_value
	$(CC) gdai247_casting_n_access.c -o gdai247_casting_n_access
	$(CC) oob.c -o oob
	$(CC) test.c -o test
	$(CC) double_pointer.c -o double_pointer
	$(CC) double_pointer_ref.c -o double_pointer_ref
	$(CC) function_pointer_single_or_double.c -o function_pointer_single_or_double
clean:
	rm -rf \
	print_addr_or_value \
	gdai247_casting_n_access \
	oob \
	test \
	double_pointer \
	double_pointer_ref \
	function_pointer_single_or_double
